NAME = RPN

CC = c++

CFLAGS = -Wall -Wextra -Werror -std=c++98

SRCS = main.cpp RPN.cpp

all : $(NAME)

$(NAME) : $(SRC)
	$(CC) $(CFLAGS)$(SRCS) -o $(NAME)

clean :

fclean : clean
	rm -rf $(NAME)

re : fclean all